name       : liblcms2
version    : 2.13.1
release    : 15
source     :
    - https://github.com/mm2/Little-CMS/releases/download/lcms2.13.1/lcms2-2.13.1.tar.gz : d473e796e7b27c5af01bd6d1552d42b45b43457e7182ce9903f38bb748203b88
license    : MIT
component  : desktop.core
homepage   : https://www.littlecms.com/
summary    : Small-footprint color management engine
description: |
    The Little Color Management System is a small-footprint color management engine, with special focus on accuracy and performance. It uses the International Color Consortium standard (ICC), which is the modern standard for color management.
emul32     : yes
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
