name       : liblcms2
version    : '2.8'
release    : 6
source     :
    - https://sourceforge.net/projects/lcms/files/lcms/2.8/lcms2-2.8.tar.gz : 66d02b229d2ea9474e62c2b6cd6720fde946155cd1d0d2bffdab829790a0fb22
license    : MIT
component  : desktop.core
summary    : Small-footprint color management engine
description: |
    The Little Color Management System is a small-footprint color management engine, with special focus on accuracy and performance. It uses the International Color Consortium standard (ICC), which is the modern standard for color management.
builddeps  :
    - pkgconfig32(glib-2.0)
    - glibc-32bit-devel
    - libgcc-32bit
emul32     : yes
setup      : |
    #Upstreamed patch
    %patch -p1 < $pkgfiles/Added-check-for-MLU-bounds.patch
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
