name        : liblcms2
version     : 2.7
release     : 3
source     :
    - http://softlayer-sng.dl.sourceforge.net/project/lcms/lcms/2.7/lcms2-2.7.tar.gz : 4524234ae7de185e6b6da5d31d6875085b2198bc63b1211f7dde6e2d197d6a53
license     : MIT
summary     : Small-footprint color management engine
description : |
    The Little Color Management System is a small-footprint color management engine, with special focus on accuracy and performance. It uses the International Color Consortium standard (ICC), which is the modern standard for color management.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
