name       : liblcms2
version    : 2.7
release    : 4
source     :
    - https://sourceforge.net/projects/lcms/files/lcms/2.7/lcms2-2.7.tar.gz : 4524234ae7de185e6b6da5d31d6875085b2198bc63b1211f7dde6e2d197d6a53
license    : MIT
summary    : Small-footprint color management engine
description: |
    The Little Color Management System is a small-footprint color management engine, with special focus on accuracy and performance. It uses the International Color Consortium standard (ICC), which is the modern standard for color management.
builddeps  :
    - pkgconfig32(glib-2.0)
    - glibc-32bit-devel
    - libgcc-32bit
emul32     : yes
setup      : |
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
