name       : liblcms2
version    : '2.9'
release    : 10
source     :
    - https://kent.dl.sourceforge.net/project/lcms/lcms/2.9/lcms2-2.9.tar.gz : 48c6fdf98396fa245ed86e622028caf49b96fa22f3e5734f853f806fbc8e7d20
license    : MIT
component  : desktop.core
summary    : Small-footprint color management engine
description: |
    The Little Color Management System is a small-footprint color management engine, with special focus on accuracy and performance. It uses the International Color Consortium standard (ICC), which is the modern standard for color management.
builddeps  :
    - pkgconfig32(glib-2.0)
emul32     : yes
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
