name       : liblcms2
version    : '2.12'
release    : 14
source     :
    - https://sourceforge.net/projects/lcms/files/lcms/2.12/lcms2-2.12.tar.gz : 18663985e864100455ac3e507625c438c3710354d85e5cbb7cd4043e11fe10f5
license    : MIT
component  : desktop.core
homepage   : https://www.littlecms.com/
summary    : Small-footprint color management engine
description: |
    The Little Color Management System is a small-footprint color management engine, with special focus on accuracy and performance. It uses the International Color Consortium standard (ICC), which is the modern standard for color management.
emul32     : yes
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
