name       : liblcms2
version    : '2.14'
release    : 16
source     :
    - https://github.com/mm2/Little-CMS/releases/download/lcms2.14/lcms2-2.14.tar.gz : 28474ea6f6591c4d4cee972123587001a4e6e353412a41b3e9e82219818d5740
license    : MIT
component  : desktop.core
homepage   : https://www.littlecms.com/
summary    : Small-footprint color management engine
description: |
    The Little Color Management System is a small-footprint color management engine, with special focus on accuracy and performance. It uses the International Color Consortium standard (ICC), which is the modern standard for color management.
emul32     : yes
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
